import { MigrationInterface, QueryRunner } from "typeorm";

export class BanksEntity1741005692043 implements MigrationInterface {
    name = 'BanksEntity1741005692043'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "banks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying, "code" character varying, "country_code" character varying, "country_name" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_3975b5f684ec241e3901db62d77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`
            INSERT INTO banks (name, slug, code, country_code, country_name) VALUES
            ('GTB', 'guaranty-trust-bank', '058', 'NG', 'Nigeria'),
            ('First Bank', 'first-bank-of-nigeria', '011', 'NG', 'Nigeria'),
            ('Access', 'access-bank', '063', 'NG', 'Nigeria'),
            ('Zenith', 'zenith-bank', '057', 'NG', 'Nigeria'),
            ('UBA', 'united-bank-for-africa', '033', 'NG', 'Nigeria'),
            ('Ecobank', 'ecobank-nigeria', '050', 'NG', 'Nigeria'),
            ('Polaris', 'polaris-bank', '076', 'NG', 'Nigeria'),
            ('FCMB', 'first-city-monument-bank', '214', 'NG', 'Nigeria'),
            ('Fidelity', 'fidelity-bank', '070', 'NG', 'Nigeria'),
            ('Stanbic', 'stanbic-ibtc-bank', '221', 'NG', 'Nigeria'),
            ('Sterling', 'sterling-bank', '232', 'NG', 'Nigeria'),
            ('Union', 'union-bank-of-nigeria', '032', 'NG', 'Nigeria'),
            ('Wema', 'wema-bank', '035', 'NG', 'Nigeria'),
            ('STD CHARTD', 'standard-chartered-bank', '068', 'NG', 'Nigeria'),
            ('Citi', 'citibank-nigeria', '023', 'NG', 'Nigeria'),
            ('Unity', 'unity-bank', '215', 'NG', 'Nigeria'),
            ('Keystone', 'keystone-bank', '082', 'NG', 'Nigeria'),
            ('Heritage', 'heritage-bank', '030', 'NG', 'Nigeria'),
            ('JPMorgan Chase', 'jpmorgan-chase', '021000021', 'US', 'United States'),
            ('Bank of America', 'bank-of-america', '026009593', 'US', 'United States'),
            ('Wells Fargo', 'wells-fargo', '121000248', 'US', 'United States'),
            ('Citibank', 'citibank', '021000089', 'US', 'United States'),
            ('U.S. Bank', 'us-bank', '122105155', 'US', 'United States'),
            ('PNC Bank', 'pnc-bank', '043000096', 'US', 'United States'),
            ('Truist', 'truist', '061113415', 'US', 'United States'),
            ('Goldman Sachs', 'goldman-sachs', '051073360', 'US', 'United States'),
            ('Capital One', 'capital-one', '056073502', 'US', 'United States'),
            ('TD Bank', 'td-bank', '031101266', 'US', 'United States'),
            ('Fifth Third Bank', 'fifth-third-bank', '042000314', 'US', 'United States'),
            ('KeyBank', 'keybank', '041001039', 'US', 'United States'),
            ('Regions Bank', 'regions-bank', '062005690', 'US', 'United States'),
            ('BMO Harris', 'bmo-harris', '071025661', 'US', 'United States'),
            ('Huntington Bank', 'huntington-bank', '044000024', 'US', 'United States'),
            ('Ally Bank', 'ally-bank', '124003116', 'US', 'United States'),
            ('American Express Bank', 'american-express-bank', '124085066', 'US', 'United States'),
            ('Discover Bank', 'discover-bank', '031100649', 'US', 'United States'),
            ('Synchrony Bank', 'synchrony-bank', '021213591', 'US', 'United States'),
            ('First Republic Bank', 'first-republic-bank', '321081669', 'US', 'United States'),
            ('HSBC', 'hsbc', '400515', 'GB', 'United Kingdom'),
            ('Barclays', 'barclays', '206554', 'GB', 'United Kingdom'),
            ('Lloyds Bank', 'lloyds-bank', '309070', 'GB', 'United Kingdom'),
            ('NatWest', 'natwest', '600001', 'GB', 'United Kingdom'),
            ('Santander UK', 'santander-uk', '090126', 'GB', 'United Kingdom'),
            ('Royal Bank of Scotland', 'royal-bank-of-scotland', '830608', 'GB', 'United Kingdom'),
            ('Halifax', 'halifax', '110002', 'GB', 'United Kingdom'),
            ('TSB Bank', 'tsb-bank', '302839', 'GB', 'United Kingdom'),
            ('Metro Bank', 'metro-bank', '234004', 'GB', 'United Kingdom'),
            ('Virgin Money', 'virgin-money', '821001', 'GB', 'United Kingdom'),
            ('Monzo', 'monzo', '040004', 'GB', 'United Kingdom'),
            ('Starling Bank', 'starling-bank', '608371', 'GB', 'United Kingdom'),
            ('Revolut', 'revolut', '230573', 'GB', 'United Kingdom'),
            ('Triodos Bank', 'triodos-bank', '162750', 'GB', 'United Kingdom'),
            ('Co-operative Bank', 'co-operative-bank', '089061', 'GB', 'United Kingdom'),
            ('Clydesdale Bank', 'clydesdale-bank', '826002', 'GB', 'United Kingdom'),
            ('Yorkshire Bank', 'yorkshire-bank', '050281', 'GB', 'United Kingdom'),
            ('Handelsbanken UK', 'handelsbanken-uk', '400723', 'GB', 'United Kingdom'),
            ('Bank of Scotland', 'bank-of-scotland', '801001', 'GB', 'United Kingdom'),
            ('Tesco Bank', 'tesco-bank', '406158', 'GB', 'United Kingdom'),
            ('Equity Bank', 'equity-bank', '068', 'KE', 'Kenya'),
            ('Kenya Commercial Bank', 'kenya-commercial-bank', '011', 'KE', 'Kenya'),
            ('Co-operative Bank of Kenya', 'co-operative-bank-of-kenya', '012', 'KE', 'Kenya'),
            ('NCBA Bank', 'ncba-bank', '070', 'KE', 'Kenya'),
            ('Absa Bank Kenya', 'absa-bank-kenya', '003', 'KE', 'Kenya'),
            ('Standard Chartered Bank Kenya', 'standard-chartered-bank-kenya', '002', 'KE', 'Kenya'),
            ('Stanbic Bank Kenya', 'stanbic-bank-kenya', '31000', 'KE', 'Kenya'),
            ('I&M Bank Kenya', 'im-bank-kenya', '057', 'KE', 'Kenya'),
            ('Diamond Trust Bank', 'diamond-trust-bank', '063', 'KE', 'Kenya'),
            ('Family Bank', 'family-bank', '07000', 'KE', 'Kenya'),
            ('Bank of Africa Kenya', 'bank-of-africa-kenya', '077', 'KE', 'Kenya'),
            ('Prime Bank Kenya', 'prime-bank-kenya', '100', 'KE', 'Kenya'),
            ('Gulf African Bank', 'gulf-african-bank', '072', 'KE', 'Kenya'),
            ('HF Group', 'hf-group', '061', 'KE', 'Kenya'),
            ('Victoria Commercial Bank', 'victoria-commercial-bank', '054', 'KE', 'Kenya'),
            ('Citibank Kenya', 'citibank-kenya', '020', 'KE', 'Kenya'),
            ('National Bank of Kenya', 'national-bank-of-kenya', '008', 'KE', 'Kenya'),
            ('Sidian Bank', 'sidian-bank', '066', 'KE', 'Kenya'),
            ('ABC Bank Kenya', 'abc-bank-kenya', '045', 'KE', 'Kenya'),
            ('Development Bank of Kenya', 'development-bank-of-kenya', '040', 'KE', 'Kenya'),
            ('GCB Bank', 'gcb-bank', '040100', 'GH', 'Ghana'),
            ('Absa Bank Ghana', 'absa-bank-ghana', '040200', 'GH', 'Ghana'),
            ('Stanbic Bank Ghana', 'stanbic-bank-ghana', '040300', 'GH', 'Ghana'),
            ('Ecobank Ghana', 'ecobank-ghana', '040400', 'GH', 'Ghana'),
            ('Fidelity Bank Ghana', 'fidelity-bank-ghana', '040500', 'GH', 'Ghana'),
            ('CalBank', 'calbank', '040600', 'GH', 'Ghana'),
            ('National Investment Bank', 'national-investment-bank', '040700', 'GH', 'Ghana'),
            ('Republic Bank Ghana', 'republic-bank-ghana', '040800', 'GH', 'Ghana'),
            ('Zenith Bank Ghana', 'zenith-bank-ghana', '040900', 'GH', 'Ghana'),
            ('Access Bank Ghana', 'access-bank-ghana', '041000', 'GH', 'Ghana'),
            ('Societe Generale Ghana', 'societe-generale-ghana', '041100', 'GH', 'Ghana'),
            ('Universal Merchant Bank', 'universal-merchant-bank', '041200', 'GH', 'Ghana'),
            ('First National Bank Ghana', 'first-national-bank-ghana', '041300', 'GH', 'Ghana'),
            ('First Atlantic Bank', 'first-atlantic-bank', '041400', 'GH', 'Ghana'),
            ('Bank of Africa Ghana', 'bank-of-africa-ghana', '041500', 'GH', 'Ghana'),
            ('OmniBSIC Bank', 'omnibsic-bank', '041600', 'GH', 'Ghana'),
            ('Ghana Export-Import Bank', 'ghana-exim-bank', '041700', 'GH', 'Ghana'),
            ('ARB Apex Bank', 'arb-apex-bank', '041800', 'GH', 'Ghana'),
            ('Consolidated Bank Ghana', 'consolidated-bank-ghana', '041900', 'GH', 'Ghana'),
            ('Deutsche Bank', 'deutsche-bank', '10070000', 'DE', 'Germany'),
            ('Commerzbank', 'commerzbank', '10040000', 'DE', 'Germany'),
            ('DZ Bank', 'dz-bank', '50070010', 'DE', 'Germany'),
            ('KfW Bank', 'kfw-bank', '50020200', 'DE', 'Germany'),
            ('Unicredit Bank (HypoVereinsbank)', 'unicredit-bank', '70020270', 'DE', 'Germany'),
            ('Landesbank Baden-Württemberg', 'lbbw', '60050000', 'DE', 'Germany'),
            ('Norddeutsche Landesbank', 'nordlb', '25050000', 'DE', 'Germany'),
            ('BayernLB', 'bayernlb', '70050000', 'DE', 'Germany'),
            ('Postbank', 'postbank', '10010010', 'DE', 'Germany'),
            ('ING-DiBa', 'ing-diba', '50010517', 'DE', 'Germany'),
            ('BNP Paribas', 'bnp-paribas', '300040000', 'FR', 'France'),
            ('Société Générale', 'societe-generale', '300030000', 'FR', 'France'),
            ('Crédit Agricole', 'credit-agricole', '300020000', 'FR', 'France'),
            ('BPCE (Banque Populaire & Caisse d’Epargne)', 'bpce', '300010000', 'FR', 'France'),
            ('La Banque Postale', 'la-banque-postale', '200410000', 'FR', 'France'),
            ('Crédit Mutuel', 'credit-mutuel', '300060000', 'FR', 'France'),
            ('HSBC France', 'hsbc-france', '300560000', 'FR', 'France'),
            ('LCL (Le Crédit Lyonnais)', 'lcl', '300070000', 'FR', 'France'),
            ('BRED Banque Populaire', 'bred-banque-populaire', '300080000', 'FR', 'France'),
            ('AXA Banque', 'axa-banque', '300090000', 'FR', 'France'),
            ('Caixa Geral de Depósitos', 'caixa-geral-de-depositos', '00100000', 'PT', 'Portugal'),
            ('Banco Santander Totta', 'banco-santander-totta', '00120000', 'PT', 'Portugal'),
            ('Novo Banco', 'novo-banco', '00180000', 'PT', 'Portugal'),
            ('Banco Comercial Português (Millennium BCP)', 'banco-comercial-portugues', '00100050', 'PT', 'Portugal'),
            ('Banco BPI', 'banco-bpi', '00100060', 'PT', 'Portugal'),
            ('Montepio', 'montepio', '00100070', 'PT', 'Portugal'),
            ('Banco CTT', 'banco-ctt', '00100080', 'PT', 'Portugal'),
            ('Banco BIG', 'banco-big', '00100090', 'PT', 'Portugal'),
            ('Banco Best', 'banco-best', '00100100', 'PT', 'Portugal'),
            ('Abanca Portugal', 'abanca-portugal', '00100110', 'PT', 'Portugal'),
            ('Banka Kombëtare Tregtare', 'bkt', '21011000', 'AL', 'Albania'),
            ('Credins Bank', 'credins-bank', '21012000', 'AL', 'Albania'),
            ('Intesa Sanpaolo Bank Albania', 'intesa-sanpaolo-albania', '21013000', 'AL', 'Albania'),
            ('Raiffeisen Bank Albania', 'raiffeisen-bank-albania', '21014000', 'AL', 'Albania'),
            ('Andbank', 'andbank', '30201000', 'AD', 'Andorra'),
            ('Morabanc', 'morabanc', '30202000', 'AD', 'Andorra'),
            ('Crèdit Andorrà', 'credit-andorra', '30203000', 'AD', 'Andorra'),
            ('Erste Group Bank', 'erste-bank', '20111000', 'AT', 'Austria'),
            ('Raiffeisen Bank International', 'raiffeisen-bank-international', '20112000', 'AT', 'Austria'),
            ('BAWAG P.S.K.', 'bawag-psk', '20113000', 'AT', 'Austria'),
            ('Unicredit Bank Austria', 'unicredit-bank-austria', '20114000', 'AT', 'Austria'),
            ('Belarusbank', 'belarusbank', '30111000', 'BY', 'Belarus'),
            ('Belgazprombank', 'belgazprombank', '30112000', 'BY', 'Belarus'),
            ('Priorbank', 'priorbank', '30113000', 'BY', 'Belarus'),
            ('KBC Bank', 'kbc-bank', '20211000', 'BE', 'Belgium'),
            ('Belfius Bank', 'belfius-bank', '20212000', 'BE', 'Belgium'),
            ('ING Belgium', 'ing-belgium', '20213000', 'BE', 'Belgium'),
            ('BNP Paribas Fortis', 'bnp-paribas-fortis', '20214000', 'BE', 'Belgium'),
            ('UniCredit Bank Mostar', 'unicredit-bank-mostar', '30311000', 'BA', 'Bosnia and Herzegovina'),
            ('Raiffeisen Bank Bosnia', 'raiffeisen-bank-bosnia', '30312000', 'BA', 'Bosnia and Herzegovina'),
            ('UniCredit Bulbank', 'unicredit-bulbank', '20411000', 'BG', 'Bulgaria'),
            ('DSK Bank', 'dsk-bank', '20412000', 'BG', 'Bulgaria'),
            ('Postbank Bulgaria', 'postbank-bulgaria', '20413000', 'BG', 'Bulgaria'),
            ('Privredna banka Zagreb', 'privredna-banka-zagreb', '20511000', 'HR', 'Croatia'),
            ('Zagrebačka banka', 'zagreb-banka', '20512000', 'HR', 'Croatia'),
            ('Bank of Cyprus', 'bank-of-cyprus', '20611000', 'CY', 'Cyprus'),
            ('Hellenic Bank', 'hellenic-bank', '20612000', 'CY', 'Cyprus'),
            ('Česká spořitelna', 'ceska-sporitelna', '20711000', 'CZ', 'Czech Republic'),
            ('Komerční banka', 'komercni-banka', '20712000', 'CZ', 'Czech Republic'),
            ('Danske Bank', 'danske-bank', '20811000', 'DK', 'Denmark'),
            ('Nykredit Bank', 'nykredit-bank', '20812000', 'DK', 'Denmark'),
            ('Swedbank Estonia', 'swedbank-estonia', '20911000', 'EE', 'Estonia'),
            ('SEB Estonia', 'seb-estonia', '20912000', 'EE', 'Estonia'),
            ('OP Financial Group', 'op-financial-group', '21011000', 'FI', 'Finland'),
            ('Nordea Finland', 'nordea-finland', '21012000', 'FI', 'Finland'),
            ('National Bank of Greece', 'national-bank-of-greece', '21111000', 'GR', 'Greece'),
            ('Alpha Bank', 'alpha-bank', '21112000', 'GR', 'Greece'),
            ('OTP Bank', 'otp-bank', '21211000', 'HU', 'Hungary'),
            ('K&H Bank', 'kh-bank', '21212000', 'HU', 'Hungary'),
            ('Landsbankinn', 'landsbankinn', '21311000', 'IS', 'Iceland'),
            ('Arion Bank', 'arion-bank', '21312000', 'IS', 'Iceland'),
            ('Allied Irish Banks', 'allied-irish-banks', '21411000', 'IE', 'Ireland'),
            ('Bank of Ireland', 'bank-of-ireland', '21412000', 'IE', 'Ireland'),
            ('Intesa Sanpaolo', 'intesa-sanpaolo', '21511000', 'IT', 'Italy'),
            ('UniCredit Italy', 'unicredit-italy', '21512000', 'IT', 'Italy'),
            ('ABN AMRO', 'abn-amro', '21911000', 'NL', 'Netherlands'),
            ('ING Netherlands', 'ing-netherlands', '21912000', 'NL', 'Netherlands'),
            ('PKO Bank Polski', 'pko-bank-polski', '22111000', 'PL', 'Poland'),
            ('mBank', 'mbank', '22112000', 'PL', 'Poland'),
            ('Banca Transilvania', 'banca-transilvania', '22211000', 'RO', 'Romania'),
            ('BRD - Groupe Société Générale', 'brd-groupe-societe-generale', '22212000', 'RO', 'Romania'),
            ('Sberbank', 'sberbank', '22311000', 'RU', 'Russia'),
            ('VTB Bank', 'vtb-bank', '22312000', 'RU', 'Russia'),
            ('Banco Santander', 'banco-santander', '22511000', 'ES', 'Spain'),
            ('BBVA', 'bbva', '22512000', 'ES', 'Spain'),
            ('Swedbank', 'swedbank', '22611000', 'SE', 'Sweden'),
            ('SEB', 'seb', '22612000', 'SE', 'Sweden'),
            ('UBS', 'ubs', '22711000', 'CH', 'Switzerland'),
            ('Credit Suisse', 'credit-suisse', '22712000', 'CH', 'Switzerland'),
            ('State Bank of India', 'sbi', '30111000', 'IN', 'India'),
            ('HDFC Bank', 'hdfc-bank', '30112000', 'IN', 'India'),
            ('ICICI Bank', 'icici-bank', '30113000', 'IN', 'India'),
            ('Punjab National Bank', 'pnb', '30114000', 'IN', 'India'),
            ('Axis Bank', 'axis-bank', '30115000', 'IN', 'India'),
            ('Bank of Baroda', 'bank-of-baroda', '30116000', 'IN', 'India'),
            ('Canara Bank', 'canara-bank', '30117000', 'IN', 'India'),
            ('Union Bank of India', 'union-bank', '30118000', 'IN', 'India'),
            ('Kotak Mahindra Bank', 'kotak-mahindra-bank', '30119000', 'IN', 'India'),
            ('IndusInd Bank', 'indusind-bank', '30120000', 'IN', 'India'),
            ('IDBI Bank', 'idbi-bank', '30121000', 'IN', 'India'),
            ('Yes Bank', 'yes-bank', '30122000', 'IN', 'India'),
            ('Indian Bank', 'indian-bank', '30123000', 'IN', 'India'),
            ('Bank of India', 'bank-of-india', '30124000', 'IN', 'India'),
            ('Central Bank of India', 'central-bank-of-india', '30125000', 'IN', 'India'),
            ('Afriland First Bank', 'afriland-first-bank', '40111000', 'CM', 'Cameroon'),
            ('BGFI Bank Cameroon', 'bgfi-bank-cameroon', '40112000', 'CM', 'Cameroon'),
            ('SCB Cameroon', 'scb-cameroon', '40113000', 'CM', 'Cameroon'),
            ('Ecobank Cameroon', 'ecobank-cameroon', '40114000', 'CM', 'Cameroon'),
            ('BICEC', 'bicec', '40115000', 'CM', 'Cameroon'),
            ('UBA Cameroon', 'uba-cameroon', '40116000', 'CM', 'Cameroon'),
            ('Standard Chartered Cameroon', 'standard-chartered-cameroon', '40117000', 'CM', 'Cameroon'),
            ('Banque Atlantique Benin', 'banque-atlantique-benin', '40211000', 'BJ', 'Benin'),
            ('Ecobank Benin', 'ecobank-benin', '40212000', 'BJ', 'Benin'),
            ('UBA Benin', 'uba-benin', '40213000', 'BJ', 'Benin'),
            ('Diamond Bank Benin', 'diamond-bank-benin', '40214000', 'BJ', 'Benin'),
            ('Coris Bank Benin', 'coris-bank-benin', '40215000', 'BJ', 'Benin'),
            ('Banque Atlantique Niger', 'banque-atlantique-niger', '40311000', 'NE', 'Niger'),
            ('Ecobank Niger', 'ecobank-niger', '40312000', 'NE', 'Niger'),
            ('UBA Niger', 'uba-niger', '40313000', 'NE', 'Niger'),
            ('Sonibank', 'sonibank', '40314000', 'NE', 'Niger'),
            ('National Bank of Egypt', 'national-bank-of-egypt', '40411000', 'EG', 'Egypt'),
            ('Banque Misr', 'banque-misr', '40412000', 'EG', 'Egypt'),
            ('CIB Egypt', 'cib-egypt', '40413000', 'EG', 'Egypt'),
            ('HSBC Egypt', 'hsbc-egypt', '40414000', 'EG', 'Egypt'),
            ('Arab African International Bank', 'arab-african-international-bank', '40415000', 'EG', 'Egypt'),
            ('Standard Bank', 'standard-bank', '40511000', 'ZA', 'South Africa'),
            ('ABSA Bank', 'absa-bank', '40512000', 'ZA', 'South Africa'),
            ('Nedbank', 'nedbank', '40513000', 'ZA', 'South Africa'),
            ('First National Bank', 'first-national-bank', '40514000', 'ZA', 'South Africa'),
            ('Capitec Bank', 'capitec-bank', '40515000', 'ZA', 'South Africa'),
            ('Attijariwafa Bank', 'attijariwafa-bank', '40711000', 'MA', 'Morocco'),
            ('BMCE Bank', 'bmce-bank', '40712000', 'MA', 'Morocco'),
            ('Banque Populaire du Maroc', 'banque-populaire-maroc', '40713000', 'MA', 'Morocco'),
            ('Société Générale Maroc', 'societe-generale-maroc', '40714000', 'MA', 'Morocco'),
            ('Crédit du Maroc', 'credit-du-maroc', '40715000', 'MA', 'Morocco'),
            ('CRDB Bank', 'crdb-bank', '40811000', 'TZ', 'Tanzania'),
            ('NMB Bank Tanzania', 'nmb-bank-tanzania', '40812000', 'TZ', 'Tanzania'),
            ('Stanbic Bank Tanzania', 'stanbic-bank-tanzania', '40813000', 'TZ', 'Tanzania'),
            ('NBC Bank Tanzania', 'nbc-bank-tanzania', '40814000', 'TZ', 'Tanzania'),
            ('KCB Bank Tanzania', 'kcb-bank-tanzania', '40815000', 'TZ', 'Tanzania');
                        
          `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "banks"`);
    }

}
