export const bankDetails = [
  {
    serial: 1,
    name: 'GTB',
    slug: 'guaranty-trust-bank',
    code: '058',
  },
  {
    serial: 2,
    name: 'First Bank',
    slug: 'first-bank-of-nigeria',
    code: '011',
  },
  {
    serial: 3,
    name: 'Access',
    slug: 'access-bank',
    code: '063',
  },
  {
    serial: 4,
    name: 'Zenith',
    slug: 'zenith-bank',
    code: '057',
  },
  {
    serial: 5,
    name: 'UBA',
    slug: 'united-bank-for-africa',
    code: '033',
  },

  {
    serial: 6,
    name: 'Ecobank',
    slug: 'ecobank-nigeria',
    code: '050',
  },

  {
    serial: 7,
    name: 'Polaris',
    slug: 'polaris-bank',
    code: '076',
  },

  {
    serial: 8,
    name: 'FCMB',
    slug: 'first-city-monument-bank',
    code: '214',
  },
  {
    serial: 9,
    name: 'Fidelity',
    slug: 'fidelity-bank',
    code: '070',
  },
  {
    serial: 10,
    name: 'Stanbic',
    slug: 'stanbic-ibtc-bank',
    code: '221',
  },
  {
    serial: 11,
    name: 'Sterling',
    slug: 'sterling-bank',
    code: '232',
  },
  {
    serial: 12,
    name: 'Union',
    slug: 'union-bank-of-nigeria',
    code: '032',
  },
  {
    serial: 13,
    name: 'Wema',
    slug: 'wema-bank',
    code: '035',
  },
  {
    serial: 14,
    name: 'STD CHARTD',
    slug: 'standard-chartered-bank',
    code: '068',
  },
  {
    serial: 15,
    name: 'Citi',
    slug: 'citibank-nigeria',
    code: '023',
  },

  {
    serial: 16,
    name: 'Unity',
    slug: 'unity-bank',
    code: '215',
  },
  {
    serial: 17,
    name: 'Keystone',
    slug: 'keystone-bank',
    code: '082',
  },
  {
    serial: 18,
    name: 'Heritage',
    slug: 'heritage-bank',
    code: '030',
  },
  {
    serial: 19,
    name: 'ASO',
    slug: 'asosavings',
    code: '401',
  },
  {
    serial: 20,
    name: 'Jaiz',
    slug: 'jaiz-bank',
    code: '301',
  },
  {
    serial: 21,
    name: 'Suntrust',
    slug: 'suntrust-bank',
    code: '100',
  },
  {
    serial: 22,
    name: 'Coronation',
    slug: 'coronation-merchant-bank',
    code: '559',
  },

  {
    serial: 23,
    name: 'Rand',
    slug: 'rand-merchant-bank',
    code: '502',
  },
  {
    serial: 24,
    name: 'Titan Bank',
    slug: 'titan-bank',
    code: '102',
  },
  {
    serial: 25,
    name: 'TAJ Bank',
    slug: 'taj-bank',
    code: '302',
  },
  {
    serial: 26,
    name: 'Globus Bank',
    slug: 'globus-bank',
    code: '00103',
  },
  {
    serial: 27,
    name: 'Providus',
    slug: 'providus-bank',
    code: '101',
  },
  {
    serial: 28,
    name: 'Abbey',
    slug: 'abbey-mortgage-bank',
    code: '801',
  },
  {
    serial: 29,
    name: 'ALAT',
    slug: 'alat-by-wema',
    code: '035A',
  },
  {
    serial: 30,
    name: 'Amju MFB',
    slug: 'amju-unique-mfb',
    code: '50926',
  },
  {
    serial: 31,
    name: 'Bainescredit',
    slug: 'bainescredit-mfb',
    code: '51229',
  },
  {
    serial: 32,
    name: 'Bowen MFB',
    slug: 'bowen-microfinance-bank',
    code: '50931',
  },
  {
    serial: 33,
    name: 'CEMCS MFB',
    slug: 'cemcs-microfinance-bank',
    code: '50823',
  },
  {
    serial: 34,
    name: 'Ekondo MFB',
    slug: 'ekondo-microfinance-bank',
    code: '562',
  },
  {
    serial: 35,
    name: 'Eyowo',
    slug: 'eyowo',
    code: '50126',
  },
  {
    serial: 36,
    name: 'Firmus MFB',
    slug: 'firmus-mfb',
    code: '51314',
  },
  {
    serial: 37,
    name: 'FSDH',
    slug: 'fsdh-merchant-bank-limited',
    code: '501',
  },
  {
    serial: 38,
    name: 'Hackman MFB',
    slug: 'hackman-microfinance-bank',
    code: '51251',
  },
  {
    serial: 39,
    name: 'Hasal MFB',
    slug: 'hasal-microfinance-bank',
    code: '50383',
  },
  {
    serial: 40,
    name: 'Ibile MFB',
    slug: 'ibile-mfb',
    code: '51244',
  },
  {
    serial: 41,
    name: 'Infinity MFB',
    slug: 'infinity-mfb',
    code: '50457',
  },
  {
    serial: 42,
    name: 'Kuda Bank',
    slug: 'kuda-bank',
    code: '50211',
  },

  {
    serial: 43,
    name: 'Links MFB',
    slug: 'links-mfb',
    code: '50549',
  },
  {
    serial: 44,
    name: 'Mayfair MFB',
    slug: 'mayfair-mfb',
    code: '50563',
  },
  {
    serial: 45,
    name: 'Mint MFB',
    slug: 'mint-mfb',
    code: '50304',
  },
  {
    serial: 46,
    name: 'One Finance',
    slug: 'one-finance',
    code: '565',
  },
  {
    serial: 47,
    name: 'PalmPay',
    slug: 'palmpay',
    code: '999991',
  },
  {
    serial: 48,
    name: 'Parallex',
    slug: 'parallex-bank',
    code: '526',
  },
  {
    serial: 49,
    name: 'Parkway',
    slug: 'parkway-ready-cash',
    code: '311',
  },
  {
    serial: 50,
    name: 'Paycom',
    slug: 'paycom',
    code: '999992',
  },
  {
    serial: 51,
    name: 'Petra MFB',
    slug: 'petra-microfinance-bank-plc',
    code: '50746',
  },
  {
    serial: 52,
    name: 'Rubies MFB',
    slug: 'rubies-mfb',
    code: '125',
  },
  {
    serial: 53,
    name: 'Sparkle MFB',
    slug: 'sparkle-microfinance-bank',
    code: '51310',
  },
  {
    serial: 54,
    name: 'TCF MFB',
    slug: 'tcf-mfb',
    code: '51211',
  },
  {
    serial: 55,
    name: 'VFD',
    slug: 'vfd',
    code: '566',
  },
];
