export const countryData = [
  // African Countries
  {
    name: 'Ghana',
    continent: 'Africa',
    dial_code: '+233',
    value: 'GH',
  },
  {
    name: 'Kenya',
    continent: 'Africa',
    dial_code: '+254',
    value: 'KE',
  },
  {
    name: 'Nigeria',
    continent: 'Africa',
    dial_code: '+234',
    value: 'NG',
  },

  // USA
  {
    name: 'United States',
    continent: 'North America',
    dial_code: '+1',
    value: 'US',
  },

  // European Countries
  {
    name: 'United Kingdom',
    continent: 'Europe',
    dial_code: '+44',
    value: 'GB',
  },
  {
    name: 'France',
    continent: 'Europe',
    dial_code: '+33',
    value: 'FR',
  },
  {
    name: 'Germany',
    continent: 'Europe',
    dial_code: '+49',
    value: 'DE',
  },
  {
    name: 'Italy',
    continent: 'Europe',
    dial_code: '+39',
    value: 'IT',
  },
  {
    name: 'Spain',
    continent: 'Europe',
    dial_code: '+34',
    value: 'ES',
  },
  {
    name: 'Netherlands',
    continent: 'Europe',
    dial_code: '+31',
    value: 'NL',
  },
  {
    name: 'Belgium',
    continent: 'Europe',
    dial_code: '+32',
    value: 'BE',
  },
  {
    name: 'Switzerland',
    continent: 'Europe',
    dial_code: '+41',
    value: 'CH',
  },
  {
    name: 'Austria',
    continent: 'Europe',
    dial_code: '+43',
    value: 'AT',
  },
  {
    name: 'Sweden',
    continent: 'Europe',
    dial_code: '+46',
    value: 'SE',
  },
  {
    name: 'Norway',
    continent: 'Europe',
    dial_code: '+47',
    value: 'NO',
  },
  {
    name: 'Denmark',
    continent: 'Europe',
    dial_code: '+45',
    value: 'DK',
  },
  {
    name: 'Finland',
    continent: 'Europe',
    dial_code: '+358',
    value: 'FI',
  },
  {
    name: 'Ireland',
    continent: 'Europe',
    dial_code: '+353',
    value: 'IE',
  },
  {
    name: 'Portugal',
    continent: 'Europe',
    dial_code: '+351',
    value: 'PT',
  },
  {
    name: 'Greece',
    continent: 'Europe',
    dial_code: '+30',
    value: 'GR',
  },
  {
    name: 'Poland',
    continent: 'Europe',
    dial_code: '+48',
    value: 'PL',
  },
  {
    name: 'Czech Republic',
    continent: 'Europe',
    dial_code: '+420',
    value: 'CZ',
  },
  {
    name: 'Hungary',
    continent: 'Europe',
    dial_code: '+36',
    value: 'HU',
  },
  {
    name: 'Slovakia',
    continent: 'Europe',
    dial_code: '+421',
    value: 'SK',
  },
  {
    name: 'Romania',
    continent: 'Europe',
    dial_code: '+40',
    value: 'RO',
  },
  {
    name: 'Bulgaria',
    continent: 'Europe',
    dial_code: '+359',
    value: 'BG',
  },
  {
    name: 'Slovenia',
    continent: 'Europe',
    dial_code: '+386',
    value: 'SI',
  },
  {
    name: 'Croatia',
    continent: 'Europe',
    dial_code: '+385',
    value: 'HR',
  },
  {
    name: 'Serbia',
    continent: 'Europe',
    dial_code: '+381',
    value: 'RS',
  },
  {
    name: 'Bosnia and Herzegovina',
    continent: 'Europe',
    dial_code: '+387',
    value: 'BA',
  },
  {
    name: 'Montenegro',
    continent: 'Europe',
    dial_code: '+382',
    value: 'ME',
  },
  {
    name: 'Albania',
    continent: 'Europe',
    dial_code: '+355',
    value: 'AL',
  },
  {
    name: 'North Macedonia',
    continent: 'Europe',
    dial_code: '+389',
    value: 'MK',
  },
  {
    name: 'Lithuania',
    continent: 'Europe',
    dial_code: '+370',
    value: 'LT',
  },
  {
    name: 'Latvia',
    continent: 'Europe',
    dial_code: '+371',
    value: 'LV',
  },
  {
    name: 'Estonia',
    continent: 'Europe',
    dial_code: '+372',
    value: 'EE',
  },
  {
    name: 'Iceland',
    continent: 'Europe',
    dial_code: '+354',
    value: 'IS',
  },
  {
    name: 'Malta',
    continent: 'Europe',
    dial_code: '+356',
    value: 'MT',
  },
  {
    name: 'Luxembourg',
    continent: 'Europe',
    dial_code: '+352',
    value: 'LU',
  },
  {
    name: 'Liechtenstein',
    continent: 'Europe',
    dial_code: '+423',
    value: 'LI',
  },
  {
    name: 'Ukraine',
    continent: 'Europe',
    dial_code: '+380',
    value: 'UA',
  },
  {
    name: 'Belarus',
    continent: 'Europe',
    dial_code: '+375',
    value: 'BY',
  },
  {
    name: 'Russia',
    continent: 'Europe',
    dial_code: '+7',
    value: 'RU',
  },
  {
    name: 'Turkey',
    continent: 'Europe',
    dial_code: '+90',
    value: 'TR',
  },
];
